layout_spectrum: 1
typography_spectrum: 0.06498389
color:
  saturation: 1
  lightness: 0.9951664
  brandStrength: 1
  brandColors:
    - '#080A05'
    - '#978E89'
    - '#383735'
    - '#D0D0D0'
    - '#E93541'
  rhythmicContrast: 1
name: A Life in the Life of.. Me!
